#lang racket
(require "square.rkt" "merge.rkt" "book.rkt")
(provide example-run)
(define (example-run)
  (define b1 (make-book-from-text "a b. c d. a c. b d. e f. g h."))
  (define b2 (make-book-from-text "a b. c d. a c. b d. e g. f h."))
  ;(define b1 (make-book-from-file "example.txt"))
  ;(define b2 (make-book-from-file "example2.txt"))
  (define s1 (make-all-squares b1))
  (define s2 (make-all-squares b2))
  (define b3 (combine-books b1 b2))
  (define s3 (new-squares b1 b2 b3))
  s3)